### PR TITLE
fix: solana indexer hang

### LINKED ISSUE #648: solana block height stuck
Image

### PR DESCRIPTION
**Pull request by ppca**
the reason why solana indexer block height stuck could be: 
1) get_transaction_with_config hangs, not getting response and hangs there forever
2) stream.next() hangs forever

in this PR, both will result in the function returning Err, then the solana client will resubscribe.

fix this issue:  https://github.com/sig-net/mpc/issues/648

### CODE REVIEW

File: chain-signatures/node/src/indexer_sol.rs [hunk 1]
```diff
@@ -327,6 +329,33 @@ impl SignatureEvent for SignBidirectionalEvent {
...
+}
+
+impl Default for TxFetchRetryConfig {
+    fn default() -> Self {
+        Self {
+            per_attempt_timeout: Duration::from_secs(3),
+            max_attempts: 5,
+            backoff_base: Duration::from_millis(300),
+            backoff_max: Duration::from_secs(5),
+            jitter_max_ms: 250,
```
[the remark this answers is not in the document]
Comment (volovyks) [reply chain-signatures/node/src/indexer_sol.rs]: Ok, I see that `jitter_max_ms` is used to generate a random value, but still, the comment is a bit off.

**Review by volovyks — COMMENTED** [review]
This is not the first place where we use exponential backoff. Can we create utils and use them across the project?

**Comment by ppca** [comment]
> This is not the first place where we use exponential backoff. Can we create utils and use them across the project?

will refactor all the retries.

File: chain-signatures/node/src/indexer_eth/mod.rs [hunk 2]
```diff
@@ -603,13 +603,74 @@ impl EthereumClient {
...
         &self,
         block_id: alloy::rpc::types::BlockId,
     ) -> Option<alloy::rpc::types::Block> {
-        match self {
-            EthereumClient::Helios(client) => client.get_block(block_id).await,
-            EthereumClient::DirectRpc(client) => client.get_block(block_id).await,
+        // Configure retry behaviour and delegate to shared retry_async helper.
+        let retry_config = crate::util::retry::RetryConfig::default();
+        // the retry helper expects the operation closure to accept one argument (attempt/index)
+        let op = |_attempt: usize| async {
```
Comment (volovyks) [inline chain-signatures/node/src/indexer_eth/mod.rs]: Let's not use clipping, especially when there is enough space for the full word. It makes reading code hard.

Comment (volovyks) [reply chain-signatures/node/src/indexer_eth/mod.rs]: In this case, it can even say what operation this is ("get_block" or something like that)

File: chain-signatures/node/src/rpc.rs [hunk 3]
```diff
@@ -929,55 +929,65 @@ async fn execute_publish(client: ChainClient, mut action: PublishAction, backlog
...
-                    .map_err(|_| ())
+        },
+        |_attempt, _reason| true,
+        |attempt, reason, sleep| match reason {
+            RetryReason::Error(_) => {
+                tracing::warn!(
+                    ?sign_id,
+                    retry_count = attempt.saturating_sub(1),
+                    elapsed = ?action.timestamp.elapsed(),
+                    "failed to publish, retrying in {sleep:?}"
```
Comment (volovyks) [inline chain-signatures/node/src/rpc.rs:974]: Would we know what chain this is?

**Review by volovyks — DISMISSED** [review]
Looks good! Nice error handling, it should give us more info in logs.

File: chain-signatures/node/src/rpc.rs (hunk 3 above)
Comment (ppca) [reply chain-signatures/node/src/rpc.rs:974]: yes! I'll add it

**Comment by volovyks** [comment]
@ppca compilation fails

**Review by volovyks — APPROVED** [review]
